import "./styles/globals.css";
import type { Metadata } from "next";
import { climateCrisis, evonshire, inter } from "./styles/fonts";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${evonshire.variable} ${climateCrisis.variable}`}>
      <body className="bg-background text-text py-4 px-6">
        {children}
      </body>
    </html>
  );
}
