import "./styles/globals.css";
import type { Metadata } from "next";
import { ibmPlexSans, sora, paytoneOne, allura } from "./styles/fonts";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ibmPlexSans.variable} ${sora.variable} ${paytoneOne.variable} ${allura.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
